defaults:
  - _self_
  - env: default
  - algo: tqc.yaml

n_envs: 6
total_timesteps: 800_000
progress_bar: True

# eval & early stopping
evaluation:
  deterministic: True
  n_eval_episodes: 20
  eval_freq: 20_000 # set to null to disable evaluation and early stopping

# reproducibility
seed: 1

wandb:
  entity: null
  project: controls_challenge_2
  save_model: True

debug: True
